name: zen_state
description: A modern, flexible state management library for Flutter that bridges the gap between local reactive state and global state management.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# No Flutter-specific assets or configurations