name: hierarchical_scopes_example
description: Example demonstrating ZenState's hierarchical scopes, ZenBuilder, and ZenControllerScope

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  zen_state:
    path: ../../  # Path to your main package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true